# Generated by Django 4.1.3 on 2022-11-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='templates/'),
        ),
    ]
